- name: Install Golang
  ansible.builtin.yum:
    name: golang
    state: installed

- name: App pre-requisites
  ansible.builtin.import_tasks: app-preq.yml

- name: Download Golang Dependencies
  ansible.builtin.yum:
    name:
      - go mod init dispatch
      - go get
      - go build

- name: SystemD setup
  ansible.builtin.import_tasks: systemd-setup.yml
