- name: Copy prometheus Configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Restart Prometheus
  ansible.builtin.shell:
    name: prometheus
    state: restarted
