- name: Install Golang
  ansible.builtin.yum:
    name: golang
    state: installed

- name: App pre-requisites
  ansible.builtin.import_tasks: app-preq.yml

- name: Download Golang Dependencies
  ansible.builtin.shell: go mod init {{component}} ; go get ; go build
  args:
      chdir: /app

- name: SystemD setup
  ansible.builtin.import_tasks: systemd-setup.yml

