- name: MongoDB Repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install MongoDB client
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: Load Schema
  ansible.builtin.shell: mongo --ssl --host dev-docdb-cluster.cluster-crn68o0cyx1v.us-east-1.docdb.amazonaws.com:27017 --sslCAFile global-bundle.pem --username docdbadmin --password roboshop1234 </app/schema/{{component}}.js

#mongo --host mongodb-dev.varundevops.online ...mongo schema



